version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "4000:4000"

    